[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://api.eva-protocol/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/binance/*"
  to = "https://eva-proxy-production.up.railway.app/binance/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/coingecko/*"
  to = "https://eva-proxy-production.up.railway.app/coingecko/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/feargreed/*"
  to = "https://eva-proxy-production.up.railway.app/feargreed/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/gmgn/*"
  to = "https://gmgn.ai/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ctnews/*"
  to = "https://cointelegraph.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/cdnews/*"
  to = "https://www.coindesk.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/decnews/*"
  to = "https://decrypt.co/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/btcmnews/*"
  to = "https://bitcoinmagazine.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/beinnews/*"
  to = "https://beincrypto.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/btcinews/*"
  to = "https://bitcoinist.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/csnews/*"
  to = "https://cryptoslate.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/bwknews/*"
  to = "https://blockworks.co/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
